insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (1, 'You captured her beauty and elegance perfectly.', '2023-11-12 20:10:35', 4, 2);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (2, 'This is a very comprehensive.', '2023-12-01 06:33:33', 19, 6);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (3, 'I love the details and the colors of your painting.', '2023-11-13 05:52:37', 24, 2);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (4, 'I think Omen is a better controller than Brimstone, because he has more mobility and versatility.', '2023-11-08 19:57:28', 11, 9);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (5, 'This is so cute and adorable.', '2023-11-04 19:12:51', 14, 11);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (6, 'Wow, this is amazing.', '2023-11-13 06:44:40', 27, 2);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (7, 'They are so beautiful and stylish, and you captured their personalities and vibes perfectly.', '2023-11-20 23:10:56', 26, 14);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (8, 'I have been using Minecraft for learning and teaching for a while, and I can attest to its effectiveness and fun.', '2023-11-13 12:37:18', 16, 4);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (9, 'I am addicted to this game!', '2023-11-08 21:47:39', 25, 9);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (10, 'I love this game!', '2023-11-22 00:55:34', 22, 5);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (11, 'How long did it take you to make this?', '2023-11-19 13:36:32', 9, 14);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (12, 'This is a very helpful guide, thank you for sharing.', '2023-11-21 07:02:47', 1, 1);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (13, 'I think the most important thing is to practice regularly and consistently, and to adjust your settings and sensitivity to suit your preferences and style.', '2023-11-20 15:32:59', 10, 7);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (14, 'I think this is the best esports event of the year, and I cant wait to see who will win the trophy.', '2023-11-20 19:58:37', 4, 15);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (15, 'This is a very effective and proven guide, thank you for sharing.', '2023-11-15 22:32:01', 15, 13);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (16, 'I think this is a great addition to the game.', '2023-11-29 04:45:31', 22, 6);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (17, 'I have been using a Pyro team with Diluc, Xiangling, Bennett, and Amber, and it works really well for me.', '2023-11-21 12:37:06', 17, 1);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (18, 'Minecraft is a great tool to stimulate creativity, collaboration, and problem-solving skills in students and teachers alike.', '2023-11-13 04:41:44', 22, 4);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (19, 'I think the most important thing is to have a positive and cooperative attitude, and to play with your team and not against them.', '2023-12-15 20:39:32', 3, 13);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (20, 'You all look stunning and accurate.', '2023-12-01 10:08:54', 20, 3);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (21, 'I love your chibi drawing of Huohuo.', '2023-11-04 10:57:27', 5, 11);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (22, 'I have been using a Pyro team with Diluc, Xiangling, Bennett, and Amber, and it works really well for me.', '2023-11-21 19:03:56', 8, 1);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (23, 'It is very strategic and engaging, and it requires a lot of thinking and planning.', '2023-11-09 14:21:58', 23, 10);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (24, 'I think the most important thing is to understand the strengths and weaknesses of each character, and to use their skills, ultimates, techniques, and elements wisely.', '2023-11-09 23:10:27', 9, 10);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (25, ' I also think Reyna is a better duelist than Phoenix, because she has more self-sustain and kill potential.', '2023-11-08 08:57:32', 25, 9);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (26, 'This is a very helpful.', '2023-11-08 16:01:43', 27, 9);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (27, 'Nice Review!', '2023-11-29 00:21:08', 28, 6);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (28, 'These are some of the best cosplays I have ever seen.', '2023-12-01 11:58:50', 5, 3);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (29, 'his is a very exciting and thrilling live blog of the League of Legends World Championship 2023', '2023-11-20 04:50:02', 7, 15);
insert into Comments (CommentID, CommentContent, CommentDate, UserID, PostID) values (30, 'I am rooting for Team Liquid, they are my favorite team.', '2023-11-01 23:52:26', 21, 8);
